# Generated by Django 5.0.14 on 2026-07-15 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apertura', models.DateTimeField(auto_now_add=True)),
                ('cierre', models.DateTimeField(blank=True, null=True)),
                ('efectivo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('efectivo_final_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('efectivo_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nota_cierre', models.TextField(blank=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_caja', to=settings.AUTH_USER_MODEL)),
                ('colmado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_caja', to='usuarios.colmado')),
            ],
            options={
                'db_table': 'sesion_caja',
                'ordering': ['-apertura'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('FIADO', 'Fiado')], max_length=15)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cambio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='COMPLETADA', max_length=10)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='clientes.cliente')),
                ('colmado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='usuarios.colmado')),
                ('sesion_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='ventas.sesioncaja')),
            ],
            options={
                'db_table': 'venta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta', to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'db_table': 'venta_detalle',
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['colmado', 'fecha'], name='venta_colmado_6e5a6b_idx'),
        ),
    ]
