# Generated by Django 5.2.1 on 2026-07-16 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(blank=True, max_length=20)),
                ('titular', models.CharField(blank=True, max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('colmado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancos', to='usuarios.colmado')),
            ],
            options={
                'db_table': 'banco_cuenta',
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='banco_cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.bancocuenta'),
        ),
    ]
