# Generated by Django 5.2.1 on 2026-08-05 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_add_marca'),
        ('ventas', '0002_bancocuenta_venta_banco_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaNCF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('01', 'Crédito Fiscal'), ('02', 'Consumo'), ('03', 'Nota de Débito'), ('04', 'Nota de Crédito'), ('11', 'Proveedores Informales'), ('13', 'Gastos Menores'), ('14', 'Régimen Especial'), ('15', 'Gubernamental')], max_length=2)),
                ('secuencia_desde', models.PositiveIntegerField()),
                ('secuencia_hasta', models.PositiveIntegerField()),
                ('secuencia_actual', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('colmado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuencias_ncf', to='usuarios.colmado')),
            ],
            options={
                'db_table': 'secuencia_ncf',
                'ordering': ['tipo', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncf', models.CharField(max_length=13, unique=True)),
                ('tipo', models.CharField(choices=[('01', 'Crédito Fiscal'), ('02', 'Consumo'), ('03', 'Nota de Débito'), ('04', 'Nota de Crédito'), ('11', 'Proveedores Informales'), ('13', 'Gastos Menores'), ('14', 'Régimen Especial'), ('15', 'Gubernamental')], max_length=2)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente_nombre', models.CharField(blank=True, default='Consumidor Final', max_length=200)),
                ('cliente_rnc', models.CharField(blank=True, max_length=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('itbis', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('VALIDA', 'Válida'), ('ANULADA', 'Anulada')], default='VALIDA', max_length=7)),
                ('colmado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='usuarios.colmado')),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura', to='ventas.venta')),
            ],
            options={
                'db_table': 'factura',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['colmado', 'fecha'], name='factura_colmado_65e4d0_idx')],
            },
        ),
    ]
