# Generated by Django 5.2.1 on 2026-08-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='motivo_anulacion',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
