# Generated by Django 5.2.1 on 2026-08-06 01:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('facturacion', '0002_factura_motivo_anulacion'),
        ('inventario', '0006_add_oferta_regla_descuento'),
        ('usuarios', '0003_usuario_permisos_extra'),
        ('ventas', '0002_bancocuenta_venta_banco_cuenta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unidad', models.CharField(default='UND', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tasa_itbis', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('itbis_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'factura_detalle',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('CREDITO', 'Crédito')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pago_factura',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente_direccion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='factura',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factura',
            name='datos_especificos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='factura',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_vencimiento_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('CREDITO', 'Crédito'), ('MIXTO', 'Mixto')], default='EFECTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='moneda',
            field=models.CharField(default='DOP', max_length=3),
        ),
        migrations.AddField(
            model_name='factura',
            name='motivo_nota',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='factura',
            name='ncf_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='facturacion.factura'),
        ),
        migrations.AddField(
            model_name='secuenciancf',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('PAGADA', 'Pagada'), ('PENDIENTE', 'Pendiente de Pago'), ('PARCIAL', 'Pago Parcial'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['colmado', 'tipo'], name='factura_colmado_372808_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['colmado', 'estado'], name='factura_colmado_eea7a0_idx'),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.factura'),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.factura'),
        ),
    ]
