# Generated by Django 5.2.1 on 2026-08-05 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0006_add_oferta_regla_descuento'),
        ('usuarios', '0002_add_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('PORCENTAJE', '% Descuento'), ('MONTO_FIJO', '$ Descuento'), ('2X1', '2×1'), ('NXPRECIO', 'N unidades por precio especial'), ('CUPON', 'Cupón de descuento')], max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_minima', models.PositiveIntegerField(default=1)),
                ('cantidad_paga', models.PositiveIntegerField(default=1)),
                ('precio_especial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('codigo_cupon', models.CharField(blank=True, max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usos', models.PositiveIntegerField(default=0)),
                ('limite_usos', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones', to='inventario.categoria')),
                ('colmado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='usuarios.colmado')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones', to='inventario.producto')),
            ],
            options={
                'db_table': 'promocion',
                'ordering': ['-creado_en'],
            },
        ),
    ]
