# Generated by Django 5.2.1 on 2026-07-16 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('FIJO', 'Gasto fijo'), ('VARIABLE', 'Gasto variable'), ('FINANCIERO', 'Gasto financiero'), ('PERDIDA', 'Pérdida'), ('ADMINISTRATIVO', 'Gasto administrativo'), ('RETIRO', 'Retiro del propietario')], max_length=15)),
                ('icono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('predefinida', models.BooleanField(default=False)),
                ('colmado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_gasto', to='usuarios.colmado')),
            ],
            options={
                'db_table': 'categoria_gasto',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comprobante', models.CharField(blank=True, max_length=50)),
                ('nota', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='gastos.categoriagasto')),
                ('colmado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='usuarios.colmado')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gasto',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['colmado', 'fecha'], name='gasto_colmado_b8c094_idx')],
            },
        ),
    ]
