# Generated by Django 5.0.14 on 2026-07-15 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='colmado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='usuarios.colmado'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='colmado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='usuarios.colmado'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='colmado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='usuarios.colmado'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('colmado', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['colmado', 'codigo_barras'], name='producto_colmado_d411ee_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['colmado', 'nombre'], name='producto_colmado_85c7aa_idx'),
        ),
    ]
