# Generated by Django 5.2.1 on 2026-07-16 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='color',
            field=models.CharField(default='#6366f1', max_length=7),
        ),
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.CharField(default='package', max_length=30),
        ),
        migrations.CreateModel(
            name='PresentacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('factor_conversion', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('codigo_barras', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='inventario.producto')),
            ],
            options={
                'db_table': 'presentacion_producto',
            },
        ),
    ]
