# Generated by Django 5.2.1 on 2026-07-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_categoria_color_categoria_icono_presentacionproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='itbis_exento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades_por_caja',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
