# Generated by Django 5.0.14 on 2026-07-17 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_itbis_exento_producto_notas_and_more'),
        ('usuarios', '0002_add_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais_origen', models.CharField(blank=True, max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('colmado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='usuarios.colmado')),
            ],
            options={
                'db_table': 'marca',
                'ordering': ['nombre'],
                'unique_together': {('colmado', 'nombre')},
            },
        ),
    ]
