# Generated by Django 5.2.1 on 2026-07-17 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_add_marca'),
        ('usuarios', '0002_add_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oferta_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='oferta_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ReglaDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_minima', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje (%)'), ('MONTO_FIJO', 'Monto fijo (RD$)')], default='PORCENTAJE', max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_descuento', to='inventario.categoria')),
                ('colmado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_descuento', to='usuarios.colmado')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_descuento', to='inventario.producto')),
            ],
            options={
                'db_table': 'regla_descuento',
                'ordering': ['cantidad_minima'],
            },
        ),
    ]
