# Generated by Django 5.2.1 on 2026-08-05 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0006_add_oferta_regla_descuento'),
        ('usuarios', '0002_add_marca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('precio_venta', 'Precio de venta'), ('precio_costo', 'Precio de costo'), ('precio_oferta', 'Precio de oferta')], max_length=20)),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_nuevo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('colmado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='usuarios.colmado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='inventario.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_precio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_precio',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['colmado', 'producto', 'campo'], name='historial_p_colmado_7187a1_idx')],
            },
        ),
    ]
