# Generated by Django 5.2.1 on 2026-08-05 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0003_ordencompra_numero_factura_and_more'),
        ('inventario', '0006_add_oferta_regla_descuento'),
        ('usuarios', '0002_add_marca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionSuplidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=200)),
                ('nota', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('monto_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('colmado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones_suplidores', to='usuarios.colmado')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones', to='compras.ordencompra')),
                ('suplidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='compras.suplidor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones_suplidores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devolucion_suplidor',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionSuplidorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo_item', models.CharField(blank=True, max_length=200)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='devoluciones_suplidores.devolucionsuplidor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones_suplidores', to='inventario.producto')),
            ],
            options={
                'db_table': 'devolucion_suplidor_item',
            },
        ),
    ]
