# Generated by Django 5.0.14 on 2026-07-17 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('VENTA', 'Venta'), ('ANULAR', 'Anulación'), ('ABONO', 'Abono'), ('COMPRA', 'Compra'), ('AJUSTE', 'Ajuste inventario'), ('LOGIN', 'Inicio sesión'), ('CAJA', 'Caja')], max_length=15)),
                ('modulo', models.CharField(max_length=50)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('colmado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_logs', to='usuarios.colmado')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_log',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['colmado', 'fecha'], name='auditoria_l_colmado_20f13e_idx'), models.Index(fields=['colmado', 'usuario', 'fecha'], name='auditoria_l_colmado_5c9ddd_idx')],
            },
        ),
    ]
