# Generated by Django 5.2.1 on 2026-08-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_add_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='permisos_extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
