# Generated by Django 5.2.1 on 2026-08-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_permisos_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'login_attempt',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='valor_anterior',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='valor_nuevo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intentos_fallidos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('VENTA', 'Venta'), ('ANULAR', 'Anulación'), ('ABONO', 'Abono'), ('COMPRA', 'Compra'), ('AJUSTE', 'Ajuste inventario'), ('LOGIN', 'Inicio sesión'), ('LOGOUT', 'Cierre sesión'), ('CAJA', 'Caja'), ('CONFIG', 'Configuración'), ('PRECIO', 'Cambio de precio'), ('LOGIN_FAIL', 'Intento de login fallido')], max_length=15),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['accion', 'fecha'], name='auditoria_l_accion_da309a_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['username', 'fecha'], name='login_attem_usernam_2b0ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip', 'fecha'], name='login_attem_ip_1859ef_idx'),
        ),
    ]
