# Generated by Django 5.2.16 on 2026-08-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_seguridad_auditoria_avanzada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pin_caja',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
