# Generated by Django 5.0.14 on 2026-07-15 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('inventario', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompraitem',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.ordencompra'),
        ),
        migrations.AddField(
            model_name='ordencompraitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_compra', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='suplidor',
            name='colmado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suplidores', to='usuarios.colmado'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='suplidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='compras.suplidor'),
        ),
    ]
