# Generated by Django 5.2.1 on 2026-07-16 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='suplidor',
            name='descuento_habitual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='suplidor',
            name='dias_credito',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='suplidor',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='suplidor',
            name='frecuencia_entrega',
            field=models.CharField(blank=True, choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], max_length=10),
        ),
        migrations.AddField(
            model_name='suplidor',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='suplidor',
            name='rnc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='suplidor',
            name='tipo_pago',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10),
        ),
        migrations.CreateModel(
            name='PagoSuplidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque')], default='EFECTIVO', max_length=15)),
                ('referencia', models.CharField(blank=True, max_length=50)),
                ('nota', models.TextField(blank=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='compras.ordencompra')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_suplidor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pago_suplidor',
                'ordering': ['-fecha'],
            },
        ),
    ]
