# Generated by Django 5.2.1 on 2026-08-05 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('usuarios', '0002_add_marca'),
        ('ventas', '0002_bancocuenta_venta_banco_cuenta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=200)),
                ('nota', models.TextField(blank=True)),
                ('metodo_devolucion', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CREDITO_CUENTA', 'Crédito en cuenta'), ('CAMBIO_PRODUCTO', 'Cambio de producto')], default='EFECTIVO', max_length=20)),
                ('monto_devuelto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESADA', 'Procesada'), ('ANULADA', 'Anulada')], default='PROCESADA', max_length=10)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones', to='clientes.cliente')),
                ('colmado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='usuarios.colmado')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='ventas.venta')),
            ],
            options={
                'db_table': 'devolucion',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='devoluciones.devolucion')),
                ('venta_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='ventas.ventadetalle')),
            ],
            options={
                'db_table': 'devolucion_item',
            },
        ),
    ]
