# Generated by Django 5.2.1 on 2026-08-10 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='max_productos',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='max_usuarios',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscripciones', to='suscripciones.plan'),
        ),
    ]
